### ISSUE TITLE
[BUG] conn.getRemoteStream() returns null on Safari 13.0.4

### ISSUE THREAD

**Issue by CoreyCole** [twilio/twilio-client.js#123]
- [x] I have verified that the issue occurs with the latest twilio.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-client.js/blob/master/CHANGELOG.md).
 - [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-client.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [x] I verified that the [Quickstart](https://github.com/TwilioDevEd/client-quickstart-js) application works in my environment.
 - [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Code to reproduce the issue:**
I've slightly modified the quickstart.js to log the result of `conn.getRemoteStream()` in the `connect` callback.
```js
device.on('connect', function (conn) {
  log('Successfully established call!');
  document.getElementById('button-call').style.display = 'none';
  document.getElementById('button-hangup').style.display = 'inline';
  volumeIndicators.style.display = 'block';
  var remoteStream = conn.getRemoteStream();
  console.log(remoteStream);
  bindVolumeIndicators(conn);
});
```

**Expected behavior:**
On chrome, this prints out a `MediaStream` object:
```
MediaStream
id: "26d83382-3908-4cda-bcfe-8451eb0b7adf"
active: true
onaddtrack: null
onremovetrack: null
onactive: null
oninactive: null
__proto__: MediaStream
```

**Actual behavior:**
On Safari, it prints `null`

**Software versions:**

 - Browser(s): Safari
 - Operating System: OSX 10.15.2, Safari 13.0.4
 - twilio.js: 1.10.0
 - Third-party libraries (e.g., Angular, React, etc.): reproducing in vanilla quick start

**Comment by charliesantos** [comment]
Hi @CoreyCole ,

Thank you for reporting.
I noticed in the code provided that you are calling `getRemoteStream` as soon as we emit device:connect event. While this is ok for some browsers, the stream might not be available during this time because adding the track/stream is an async process, and we don't currently emit an event for when it becomes ready. This is very noticeable on Safari as it takes more time to add the track/stream. We do however have events that we emit after adding the track/stream. What do you think about using the connection:volume event?
```
    connection.on('volume', () => {
      console.log(connection.getRemoteStream());
    });
```
This event is not intended for this specific use case, but it ensures the stream is available when you call `getRemoteStream`. connection:volume event also fires constantly so please keep that in mind.

Thanks,
Charlie
