### ISSUE TITLE
[FEATURE] audio volume events for specific speakers in conference

### ISSUE THREAD

**Issue by mesqueeb** [twilio/twilio-client.js#178]
**Is your feature request related to a problem? Please describe.**

In my app, I use this event listener to check the input volume of the speaker:
```ts
this.twilioConnection.on("volume", (inputVolume: number) => {
                this.twilioInputVolume = inputVolume
            })
```

The twilio connection is a voice connection but it's a **Conference call**.

I have a list of participants synced through my database (firestore).

However, I would like each participant to have an audio visual (bouncing audio bars).

For this audio visual per participant, **I need to know the `outputVolume` on a per-participant basis.**

**Describe the solution you'd like**

I'm basically looking for something like this:
```ts
type OutputVolumePerParticipant = {
  /**
   * the outputVolume per participant.
   * (A percentage of maximum volume represented by a floating point number between 0.0 and 1.0, inclusive. This value represents a range of relative decibel values between -100dB and -30dB.)
   */
  [To: string]: number
}

this.twilioConnection.on("outputVolumeWithDetails", (outputVolumePerParticipant: OutputVolumePerParticipant) => {
                // console.log(`outputVolumePerParticipant → `, outputVolumePerParticipant)
            })
```

**Describe alternatives you've considered**

Please tell me if there is a way to achieve this, or a work around.

**Comment by charliesantos** [comment]
Hi @mesqueeb , this feature is currently not supported by conference. Please contact support@twilio.com or through your Twilio Console and submit a feature request for Conference.

As a workaround, you might need to implement it outside of voice sdk. You can continue to use the connection's volume event and save the volume levels to a real time db so that other participant can read the volume levels.

**Comment by charliesantos** [comment]
@mesqueeb ,  [Twilio Sync](https://www.twilio.com/sync) might work for this use case.

**Comment by mesqueeb** [comment]
@charliesantos I looked into sync, but that's just a completely different approach.
In that case it's the same as using our realtime database (we use Firestore) to just update every participants microphone audio input as percentage every 200 ms.
That's a valid workaround, but kind of defeats the purpose of using twilio-client js sdk...

I would love it is this feature request could be considered, as there is a lot of manual infrastructure we can avoid if this was available in the twilio client js sdk:
```ts
type OutputVolumePerParticipant = {
  /**
   * the outputVolume per participant.
   * (A percentage of maximum volume represented by a floating point number between 0.0 and 1.0, inclusive. This value represents a range of relative decibel values between -100dB and -30dB.)
   */
  [To: string]: number
}

twilioConnection.on("outputVolumeWithDetails", (outputVolumePerParticipant: OutputVolumePerParticipant) => {
  // console.log(`outputVolumePerParticipant → `, outputVolumePerParticipant)
})
```

best regards

**Comment by charliesantos** [comment]
Hi @mesqueeb , thank you for providing additional details. I understand the use case and we will consider this feature in client js sdk. But to fully get this to work, you will also need to submit a feature request to Conferencing APIs by contacting support@twilio.com.

I will close this ticket for now since we don't have action items at this time. Please feel free to send follow ups in this ticket.

Thank you,
Charlie
