### ISSUE TITLE
[FEATURE] Event names on Connection should be a string literal

### ISSUE THREAD

**Issue by mesqueeb** [twilio/twilio-client.js#207]
**Is your feature request related to a problem? Please describe.**
I can't know the possible events on Connection from just TS.

**Describe the solution you'd like**
Instead of currently `Connection extends EventEmitter` which defaults to a _generic_ `string` for events.

The Connection interface should implement it's own signature for the `on()` function with a string literal for possible event names.

Currently there's 0 type checking on these event names in my screenshot, so a simple spelling mistake (like the bottom one with an empty string) won't show any TS errors in VSCode...

<img width="475" alt="Screenshot 2020-08-02 12 28 46" src="https://user-images.githubusercontent.com/3253920/89114841-b8a4c380-d4bb-11ea-9f40-59e8b04251a3.png">

**Comment by charliesantos** [comment]
This is a great suggestion @mesqueeb . Unfortunately, this is also considered a breaking change. Our customers who are already using string literals will have to update their code. We will include this to our next major release instead.

**Comment by mesqueeb** [comment]
@charliesantos in what way would they have to update their code?

I'm pretty sure no update or change is required with string literals. : )

Can you give an example of how they would need to update their code ?

**Comment by charliesantos** [comment]
For example, current signature of `connection.on` is `Connection.on(eventName: string, handler: Function)`. To make it strongly typed, we would update the signature to `Connection.on(eventName: Connection.Events, handler: Function)`.
If the existing code that are subscribed to `connection.on` is using `connection.on('error', handler)` for example, this would throw a syntax error because the literal string `error` is not of type `Connection.Events` although internally, they are both `strings`.

Unless I'm not fully understanding your suggestion. If so, please provide an example.
