### ISSUE TITLE
[BUG] Audio output channel is duplicated when using USB headset after getUserMedia()

### ISSUE THREAD

**Issue by geoffliddiard** [twilio/twilio-client.js#212]
- [x] I have verified that the issue occurs with the latest twilio.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-client.js/blob/master/CHANGELOG.md).
 - [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-client.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [ ] I verified that the [Quickstart](https://github.com/TwilioDevEd/client-quickstart-js) application works in my environment.
 - [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Code to reproduce the issue:**

Plug in a USB-A headset, visit https://networktest.twilio.com/ without any prior microphone permission granted, after accepting the permissions request, you will hear duplicate audio output. I have this issue with our app using twilio-client version 1.12.3. If you refresh the page, the audio output works as expected.

**Expected behavior:**

Using a USB-A headset I should only hear a single audio output

**Actual behavior:**

Using a USB-A headset I hear duplicated audio output

**Software versions:**

 - [x] Browser(s): Chrome Version 84.0.4147.135
 - [x] Operating System: macOS 10.15.6
 - [x] twilio.js: 1.12.3, 1.9.
 - [x] Third-party libraries (e.g., Angular, React, etc.): none

**Comment by charliesantos** [comment]
Hi @geoffliddiard thank you for reporting. Unfortunately, I'm not able to reproduce. Here are the steps I tried.
1. Plug in USB-A headset
2. visit https://networktest.twilio.com
3. Allow device permission when prompted
After permission is granted, I can hear the audio just fine.

I have a few questions:
- What is the model of your USB-A device?
- Does it happen on a different headset?
- Does it happen on other browsers? Can you also please try updating to Chrome 85 and see if the issue is resolved?
- When you say duplicate audio output, do you mean you hear the audio on USB headset and default macbook speaker at the same time?

**Comment by charliesantos** [comment]
I'll close due to inactivity. Please feel free to follow up in this ticket. Thank you.
