### ISSUE TITLE
Catch busy call event (browser -> mobile, mobile cancel the call)

### ISSUE THREAD

**Issue by jaysonhubt** [twilio/twilio-client.js#280]
Hi,
I use twilio client to make a call to mobile.
The mobile was ringing and I cancel it.
But the connection in browser is still open, only play busy tone.
Show how I know a call is busy by code?

Thanks for your supporting!

**Comment by ryan-rowland** [comment]
Hi Jayson,
Sorry this wasn't responded to earlier. This issue is something our support staff would be better equipped to handle, as they are well-versed in the full stack of Programmable Voice rather than just the SDK. If you're still having this issue, please reach out to our support team with a ticket. Thanks!
