### ISSUE TITLE
[Feature Request] Include TypeScript definitions in released npm package

### ISSUE THREAD

**Issue by keichan34** [twilio/twilio-client.js#36]
**Is your feature request related to a problem? Please describe.**
It seems like a lot of the code is already written in TypeScript, but the definitions aren't being exported in the published npm package. This makes using this library in a TypeScript app a little cumbersome.

**Describe the solution you'd like**
Exported TypeScript definitions.

**Describe alternatives you've considered**

**Additional context**
https://github.com/microsoft/TypeScript/issues/7546

It looks like as long as allowJs: true is set, declarations may not be generated...

**Comment by ryan-rowland** [comment]
Hi @keichan34!

Thanks for bringing this up. The whole public object model is in TypeScript, so it would make a lot of sense to be able to include our definitions to be consumed by other TypeScript projects. As the link you've added shows, it's not supported by default since we're not completely moved into TypeScript yet. We'll create an internal ticket to do some research on our end and see how we might be able to bypass this limitation.

In the mean time, feel free to open a PR if you manage to find a solution on your end, or share any useful links you run across!

**Comment by adisreyaj** [comment]
Is there any update on this?

**Comment by charliesantos** [comment]
Created internal ticket [CLIENT-7427](https://issues.corp.twilio.com/browse/CLIENT-7427) to be added for future releases.

**Comment by charliesantos** [comment]
This has been added in 1.10.1.
